" 兼容模式
if &compatible
    set nocompatible
endif

" 设置主要配置目录
let $VIM_PATH=fnamemodify(resolve(expand('<sfile>:p')),':h:h')


" 判断运行时目录，是否包含主要配置目录
if &runtimepath !~# $VIM_PATH
    set runtimepath ^= $VIM_PATH " 添加路径
endif

let $DATA_PATH= g:etc#cache_path

augroup MyAutoCmd
    autocmd!
    autocmd CursorHold *? syntax sync minlines=300
augroup END

" Disable vim distribution plugins
let g:loaded_getscript = 1
let g:loaded_getscriptPlugin = 1
let g:loaded_gzip = 1
let g:loaded_logiPat = 1
let g:loaded_matchit = 1
let g:loaded_matchparen = 1
let g:netrw_nogx = 1 " disable netrw's gx mapping.
let g:loaded_rrhelper = 1  " ?
let g:loaded_shada_plugin = 1  " ?
let g:loaded_tar = 1
let g:loaded_tarPlugin = 1
let g:loaded_tutor_mode_plugin = 1
let g:loaded_2html_plugin = 1
let g:loaded_vimball = 1
let g:loaded_vimballPlugin = 1
let g:loaded_zip = 1
let g:loaded_zipPlugin = 1"

" 启动时执行
if has('vim_starting')
    " 全局映射”
    let g:mapleader="\<space>"
    let g:maplocalleader=';'

    " 取消如下键位默认设置
    nnoremap <Space>  <Nop>
    xnoremap <Space>  <Nop>
    nnoremap ,        <Nop>
    xnoremap ,        <Nop>
    nnoremap ;        <Nop>
    xnoremap ;        <Nop>

endif

call etc#init()
call etc#util#source_file('layers/+thinkvim/config.vim')
call etc#util#source_file('core/general.vim')
call etc#util#source_file('core/filetype.vim')
call etc#util#source_file('core/mappings.vim')



